# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "new-devops-project-artemb-21"
    encrypt      = true
    key          = "./terraform.tfstate"
    region       = "eu-north-1"
    use_lockfile = true
  }
}
